version: '3.8'
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=events,sqs
      - DEBUG=1
      - PROVIDER_OVERRIDE_EVENTS=v2
    ports:
      - "4566:4566"
    volumes:
      - "./.localstack:/temp/localstack"
